# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Gopi Subramanian
tagline:             'Mainly the Science in Data Science, occasionally the Art...'
description:         'Random musing on some machine learning algorithms.'
url:                 http://subramgo.github.io
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Gopi Subramanian
  url:               http://subramgo.github.io/
  email:             gopi.subramanian@gmail.com

# Custom vars
version:             1.0.0

# Google services
google_analytics: UA-100578402-1

