# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Gopi Subramanian
tagline:             'Mainly the Science in Data Science, occasionally the Art...'
description:         'A blog listing some interesting data, algorithms and small data science projects.'
url:                 http://subramgo.github.io/
baseurl:             'http://subramgo.github.io/'
paginate:            5

# About/contact
author:
  name:              Gopi Subramanian
  url:               http://subramgo.github.io/
  email:             gopi.subramanian@gmail.com

# Custom vars
version:             1.0.0
